services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: todolist_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./projet_devops_backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: azerty
      DB_NAME: todolist_db
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: sh -c "sleep 8 && npm run start"

  frontend:
    build: ./projet_devops_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql-data:
