name: Backend CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todolist_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s 
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      - name: Make jest executable
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests
        run: npm test


  build-and-push:
    runs-on: ubuntu-latest
    needs: test-backend
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todolist-backend:latest