name: Deploy AKS

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"] # nom exact des workflows des autres repos
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Deploy AKS with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/
