name: Frontend CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projet_devops_frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install frontend dependencies
        run: npm install

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli@15

      - name: Run frontend unit tests
        run: ng test --watch=false --browsers=ChromeHeadless
        
  build-and-push:
    runs-on: ubuntu-latest
    needs: test-frontend
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: projet_devops_frontend
          file: projet_devops_frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todolist-frontend:latest
